import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import './responsive.css';
import Header from '@/components/header/header';
import ThemeProvider from '@/context/ThemeProvider';
import Footer from '@/components/footer/footer';
import { ClerkProvider } from '@clerk/nextjs'
import { esES } from "@clerk/localizations";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={esES} appearance={{
      variables: {
        colorPrimary: "#3bb77e",
      }
    }}>
      <html lang="en">
        <body>
          <ThemeProvider>
              <Toaster position='top-right'/>
              <Header />
                {children}
              <Footer/>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
